# Generated by Django 4.2.11 on 2024-06-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hustings", "0010_husting_created_husting_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="husting",
            name="status",
            field=models.CharField(
                choices=[
                    ("suggested", "Suggested"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("unpublished", "Unpublished"),
                ],
                default=False,
            ),
        ),
    ]
