# Generated by Django 4.2.11 on 2024-06-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hustings", "0011_husting_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="husting",
            name="location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Descriptive text or address of the location (if online write 'internet')",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="husting",
            name="starts",
            field=models.DateTimeField(
                help_text="The date and time the event starts"
            ),
        ),
        migrations.AlterField(
            model_name="husting",
            name="status",
            field=models.CharField(
                choices=[
                    ("suggested", "Suggested"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("unpublished", "Unpublished"),
                ],
                default="suggested",
            ),
        ),
        migrations.AlterField(
            model_name="husting",
            name="title",
            field=models.CharField(
                help_text="The title or topic of the husting", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="husting",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="A webpage where people can find more information and/or sign up to attend",
                max_length=800,
                verbose_name="URL",
            ),
        ),
    ]
